### ISSUE TITLE
Colour config not loading on linux

### ISSUE THREAD

**Issue by al1-ce** [Graumen/TrueTooltips#3]
System is:
tModLoader v0.11.8.8
Ubuntu 22.04
True Tooltips v1.3.1.1

Config is not loading for some reason and all colour related settings are defaulted to opaque white

**Comment by al1-ce** [comment]
Modlist is:
"TerrariaOverhaul",
  "WingSlot",
  "MagicStorage",
  "RecipeBrowserToMagicStorage",
  "RecipeBrowser",
  "BossChecklist",
  "VeinMiner",
  "WeaponOutOverhaulCompat",
  "WeaponOut",
  "AutoTrash",
  "ShorterRespawn",
  "CalamityMod",
  "CalamityModMusic",
  "TrueTooltips",
  "ColoredLightPets"

**Comment by Graumen** [comment]
Unfortunately i'm not able to test on linux. Does it happen when not using other mods? I don't know what could be causing this as there's nothing special about the config.

**Comment by al1-ce** [comment]
I suspect paths because it's able to save config but not load

I'll do a bit of testing without mods later

**Comment by al1-ce** [comment]
I get same results without other mods

**Comment by Graumen** [comment]
I just released an update that might fix the issue.

**Comment by al1-ce** [comment]
Well.. It crashed terraria

**Comment by Graumen** [comment]
That shouldn't happen. I just changed the formatting of the config thinking that it caused a JsonReaderException. Can you provide your client.log? And does it work with version 1.3? Sorry for asking so much of you.
