### ISSUE TITLE
tModLoader crashes when this mod is enabled and you mouse over the Main Menu shortcuts in the bottom left

### ISSUE THREAD

**Issue by DarkVamprism** [Graumen/TrueTooltips#4]
Enabling the mod means that mousing over the shortcuts results in a crash

Shortcuts:
![image](https://user-images.githubusercontent.com/19684420/181878231-aa7e29e5-f169-4b73-a9f8-9440ce93b213.png)

Error:
![image](https://user-images.githubusercontent.com/19684420/181878190-2ee1501a-f665-400e-82ca-926017a19ca7.png)

**Comment by Graumen** [comment]
Thanks for letting me know. I just released a fix.
